### ISSUE TITLE
[FR]: TD | $100 | Critical | Customer wants the shiny new feature

### ISSUE THREAD

**Issue by gauravdhy** [gauravdhy/issue-forms#15]
### Customer

TD

### ARR

$100

### Revenue Impact (+ Net New / - Loss)

-$20

### Revenue Impact Probability

No Impact

### Details

New ask from the customer!

### Priority Level

Critical

### What action would you like the engineering/product to take?

Build the new feature

### Customer Business Impact

- [X] Deal/Upsell Blocker
- [ ] Renewal Blocker
- [ ] Customer Sentiment Issue
- [ ] Nice To Have

### Customer requested target timeline (if any)?

By Jan 31st, 2023

### Product Area

- [X] SSH
- [X] K8
- [ ] Database
- [ ] Application
- [ ] Desktop
- [ ] Integrations

### Other Customers?

ABC

### Linked Issues

https://github.com/gravitational/teleport/issues/20289
