### ISSUE TITLE
[FR or BR]: Customer | ARR | Priority | Description

### ISSUE THREAD

**Issue by gauravdhy** [gauravdhy/issue-forms#18]
### Customer

Test Customer

### ARR

$100

### Revenue Impact (+ Net New / - Loss)

-$20

### Revenue Impact Probability

High

### Details

New ask from the customer!

### What is the potential impact of not addressing this request?

- [ ] Unknown (It is a Support Request)
- [X] Customer Sentiment Issue
- [ ] Nice To Have

### Desired Outcome?

Address this issue.

### Customer requested target timeline (if any)?

Q1 2023

### Product Area

- [X] SSH
- [X] K8
- [ ] Database
- [ ] Application
- [ ] Desktop
- [ ] Integrations

### Other Customers?

None

### Linked Issues (separate by ; )

None

### Effort Estimate

None

### Engineering Committed Timeframe/Release

TBD

**Comment by gauravdhy** [comment]
Planning to deliver in Q2 2023.
