### ISSUE TITLE
[FR or BR]: Customer/Prospect | ARR | Priority | Description

### ISSUE THREAD

**Issue by gauravdhy** [gauravdhy/issue-forms#21]
### Customer/Prospect

Test Customer

### ARR

$100

### Revenue Impact (+ Net New / - Loss)

-$20

### Revenue Impact Probability

Medium

### Details

New ask from the customer!

### What is the potential non-revenue impact?

- [ ] Unknown (It is a Support Request)
- [X] SLA Breach (It is a Support Request)
- [ ] Customer/Prospect Sentiment Issue
- [ ] Nice To Have

### Desired Outcome?

new request

### Customer/Prospect requested target timeline (if any)?

None

### Product Area

- [X] SSH
- [X] K8
- [ ] Database
- [ ] Application
- [ ] Desktop
- [ ] Integrations

### Other Customers?

None

### Linked Issues (separate by ; )

None

### Effort Estimate

None

### Engineering Committed Timeframe/Release

TBD

**Comment by gauravdhy** [comment]
@gauravdhy Test Message.
